/**
 * SignedFill EIP-712 signing hash verification tests.
 *
 * These tests verify that the TypeScript SDK computes the same EIP-712
 * domain separator, struct hash, and signing hash as the Rust implementation
 * for fill-specific scenarios.
 *
 * Fill vectors represent filler authorization - the filler authorizes transfer
 * of tokens they provide to satisfy order outputs. The permitted tokens exactly
 * match the output tokens/amounts.
 *
 * The test vectors are generated by running:
 * cargo t -p signet-types fill_signing_vectors -- --nocapture --ignored
 */
import { describe, expect, it } from "vitest";
import type { Address, Hex } from "viem";
import {
  eip712Components,
  eip712SigningHash,
  permit2DomainSeparator,
  permitBatchWitnessStructHash,
} from "../src/signing/eip712.js";
import type { Eip712SigningParams } from "../src/signing/eip712.js";
import vectors from "./fill-vectors.json";

/**
 * Serialized test vector from Rust.
 */
interface SerializedVector {
  name: string;
  chain_id: number;
  order_contract: Address;
  permitted: Array<{
    token: Address;
    amount: Hex;
  }>;
  nonce: Hex;
  deadline: Hex;
  outputs: Array<{
    token: Address;
    amount: Hex;
    recipient: Address;
    chain_id: number;
  }>;
  expected_domain_separator: Hex;
  expected_struct_hash: Hex;
  expected_signing_hash: Hex;
}

/**
 * Parse a serialized vector into Eip712SigningParams.
 */
function parseVector(v: SerializedVector): Eip712SigningParams {
  return {
    chainId: BigInt(v.chain_id),
    orderContract: v.order_contract,
    permitted: v.permitted.map((p) => ({
      token: p.token,
      amount: BigInt(p.amount),
    })),
    nonce: BigInt(v.nonce),
    deadline: BigInt(v.deadline),
    outputs: v.outputs.map((o) => ({
      token: o.token,
      amount: BigInt(o.amount),
      recipient: o.recipient,
      chainId: o.chain_id,
    })),
  };
}

describe("SignedFill EIP-712 signing hash verification", () => {
  const testVectors = vectors as SerializedVector[];

  for (const v of testVectors) {
    describe(v.name, () => {
      const params = parseVector(v);

      it("produces correct domain separator", () => {
        const domainSep = permit2DomainSeparator(params.chainId);
        expect(domainSep.toLowerCase()).toBe(
          v.expected_domain_separator.toLowerCase()
        );
      });

      it("produces correct struct hash", () => {
        const structHash = permitBatchWitnessStructHash(params);
        expect(structHash.toLowerCase()).toBe(
          v.expected_struct_hash.toLowerCase()
        );
      });

      it("produces correct signing hash", () => {
        const signingHash = eip712SigningHash(params);
        expect(signingHash.toLowerCase()).toBe(
          v.expected_signing_hash.toLowerCase()
        );
      });

      it("eip712Components returns all correct values", () => {
        const components = eip712Components(params);
        expect(components.domainSeparator.toLowerCase()).toBe(
          v.expected_domain_separator.toLowerCase()
        );
        expect(components.structHash.toLowerCase()).toBe(
          v.expected_struct_hash.toLowerCase()
        );
        expect(components.signingHash.toLowerCase()).toBe(
          v.expected_signing_hash.toLowerCase()
        );
      });
    });
  }
});

describe("Fill-specific EIP-712 test cases", () => {
  it("minimal fill signing hash matches expected", () => {
    const params: Eip712SigningParams = {
      chainId: 1n,
      orderContract: "0x0000000000000000000000000000000000000000",
      permitted: [
        {
          token: "0x0000000000000000000000000000000000000000",
          amount: 0n,
        },
      ],
      nonce: 0n,
      deadline: 0n,
      outputs: [
        {
          token: "0x0000000000000000000000000000000000000000",
          amount: 0n,
          recipient: "0x0000000000000000000000000000000000000000",
          chainId: 1,
        },
      ],
    };

    const signingHash = eip712SigningHash(params);
    expect(signingHash.toLowerCase()).toBe(
      "0x336c8f9f25cba888cd3830f3357ac234a2a0b132213330b25a9ce2fba78934c9"
    );
  });

  it("multi-token fill with WETH and USDC", () => {
    const params: Eip712SigningParams = {
      chainId: 1n,
      orderContract: "0x96f44ddc3bc8892371305531f1a6d8ca2331fe6c",
      permitted: [
        {
          token: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
          amount: 500_000_000_000_000_000n, // 0.5 WETH
        },
        {
          token: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
          amount: 1_000_000_000n, // 1000 USDC
        },
      ],
      nonce: 42n,
      deadline: 1750000000n,
      outputs: [
        {
          token: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
          amount: 500_000_000_000_000_000n,
          recipient: "0x7777777777777777777777777777777777777777",
          chainId: 1,
        },
        {
          token: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
          amount: 1_000_000_000n,
          recipient: "0x7777777777777777777777777777777777777777",
          chainId: 1,
        },
      ],
    };

    const signingHash = eip712SigningHash(params);
    expect(signingHash.toLowerCase()).toBe(
      "0x341d2147b9a13923c0828e5521b2bf1153af3e14c302d4ae942f91ed9592719e"
    );
  });

  it("cross-chain fill with outputs to mainnet and rollup", () => {
    const params: Eip712SigningParams = {
      chainId: 1n,
      orderContract: "0x96f44ddc3bc8892371305531f1a6d8ca2331fe6c",
      permitted: [
        {
          token: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
          amount: 1_000_000_000n, // 1000 USDC total
        },
      ],
      nonce: 88888n,
      deadline: 1800000000n,
      outputs: [
        {
          token: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
          amount: 500_000_000n, // 500 USDC to mainnet
          recipient: "0x3333333333333333333333333333333333333333",
          chainId: 1,
        },
        {
          token: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
          amount: 500_000_000n, // 500 USDC to rollup
          recipient: "0x4444444444444444444444444444444444444444",
          chainId: 519,
        },
      ],
    };

    const signingHash = eip712SigningHash(params);
    expect(signingHash.toLowerCase()).toBe(
      "0xc1e8ba29e37c94945ae5a4895675bc1e48a2f2c735d319694ea386c1904db617"
    );
  });

  it("large amount fill exceeding JS safe integer on rollup", () => {
    const params: Eip712SigningParams = {
      chainId: 519n,
      orderContract: "0x000000000000007369676e65742d6f7264657273",
      permitted: [
        {
          token: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
          amount: 50_000_000_000_000_000_000_000n, // 50,000 WETH
        },
      ],
      nonce: BigInt("0xffffffffffffffff"), // u64::MAX
      deadline: BigInt("0xffffffffffffffff"), // u64::MAX
      outputs: [
        {
          token: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
          amount: 50_000_000_000_000_000_000_000n,
          recipient: "0x9999999999999999999999999999999999999999",
          chainId: 1,
        },
      ],
    };

    const signingHash = eip712SigningHash(params);
    expect(signingHash.toLowerCase()).toBe(
      "0x9f40af7da8b78654d64c937c0e15c9c05a0cfa81756fba5b9ae7f4a22d69a116"
    );
  });

  it("signet rollup fill", () => {
    const params: Eip712SigningParams = {
      chainId: 519n,
      orderContract: "0x000000000000007369676e65742d6f7264657273",
      permitted: [
        {
          token: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
          amount: 10_000_000_000n, // 10,000 USDC
        },
      ],
      nonce: 123456789n,
      deadline: 1850000000n,
      outputs: [
        {
          token: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
          amount: 10_000_000_000n,
          recipient: "0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef",
          chainId: 519,
        },
      ],
    };

    const signingHash = eip712SigningHash(params);
    expect(signingHash.toLowerCase()).toBe(
      "0xff671db7bf069cf756bafadadf2905608fb35d89dd4b8d0a65ea5fe66bcca882"
    );
  });
});
